from rendering.battle.assets import HEIGHT, WIDTH

MARGIN = 36
OPPONENT_SPRITE_MAX_SIZE = 374
PLAYER_SPRITE_MAX_SIZE = 528
OPPONENT_SPRITE_ANCHOR = (930, 100)
PLAYER_SPRITE_ANCHOR = (70, HEIGHT - 30)
DEFAULT_GIF_FRAME_DURATION_MS = 100

MAX_BATTLE_GIF_FRAMES = 20
BATTLE_GIF_OUTPUT_SCALE = 0.62
BATTLE_GIF_PALETTE_COLORS = 128
DISCORD_MAX_GIF_BYTES = 7_500_000

__all__ = [
    "BATTLE_GIF_OUTPUT_SCALE",
    "BATTLE_GIF_PALETTE_COLORS",
    "DEFAULT_GIF_FRAME_DURATION_MS",
    "DISCORD_MAX_GIF_BYTES",
    "HEIGHT",
    "MARGIN",
    "MAX_BATTLE_GIF_FRAMES",
    "OPPONENT_SPRITE_ANCHOR",
    "OPPONENT_SPRITE_MAX_SIZE",
    "PLAYER_SPRITE_ANCHOR",
    "PLAYER_SPRITE_MAX_SIZE",
    "WIDTH",
]
