SPRITE_SIZE = 96

COLUMNS = 5
ROWS = 3

POKEMON_PER_PAGE = COLUMNS * ROWS

CELL_WIDTH = 128
CELL_HEIGHT = 150

PADDING_X = 32
PADDING_Y = 20

FOOTER_HEIGHT = 48

WIDTH = PADDING_X * 2 + COLUMNS * CELL_WIDTH

HEIGHT = PADDING_Y * 2 + ROWS * CELL_HEIGHT + FOOTER_HEIGHT
